# When a push is made to master, build the project and re-commit the files
# to the repository. This will trigger the build workflow again, but this
# time the build will be skipped because the commit message will contain
# [skip ci].

name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "tarwich@gmail.com"
          env
          git add .
          git commit -m "Build site [skip ci]"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
