# When a push is made to master, build the project and re-commit the files
# to the repository. This will trigger the build workflow again, but this
# time the build will be skipped because the commit message will contain
# [skip ci].

name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - name: Update pull request
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          add: 'dist'
          fetch: false
          push: true
